name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: pip install -r requirements.txt        
      
    - name: Build
      run:  python ./mnist.py
        
    - name: Commit
      run: |
        git add -A && git -c user.name='ci' -c user.email='ci@email.org' commit -m 'deploy' 
  
    - uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: tfjs-minist
        heroku_email: michel.promonet@free.fr
